CREATE TABLE TB_OPERADORAS (
  REGISTRO_OPERADORA CHAR(6) NOT NULL UNIQUE,
  PRIMARY KEY (REGISTRO_OPERADORA),

  CNPJ CHAR(14) NOT NULL UNIQUE,
  RAZAO_SOCIAL VARCHAR(140),
  NOME_FANTASIA VARCHAR(140),
  MODALIDADE VARCHAR(100),
  LOGRADOURO VARCHAR(40),
  NUMERO VARCHAR(20),
  COMPLEMENTO VARCHAR(40),
  BAIRRO VARCHAR(30),
  CIDADE VARCHAR(30),
  UF CHAR(2),
  CEP CHAR(8),
  DDD CHAR(4),
  TELEFONE VARCHAR(20),
  FAX VARCHAR(20),
  EMAIL VARCHAR(255),
  REPRESENTANTE VARCHAR(50),
  CARGO_REPRESENTANTE VARCHAR(40),
  REGIAO_COMERCIALIZACAO INT CHECK (REGIAO_COMERCIALIZACAO BETWEEN 1 AND 6),
  DATA_REGISTRO_ANS DATE
);

CREATE TABLE TB_CONTA_CONTABIL (
  COD_CONTABIL INT NOT NULL,
  PRIMARY KEY (COD_CONTABIL),

  REGISTRO_OPERADORA CHAR(6) NOT NULL,
  FOREIGN KEY (REGISTRO_OPERADORA) REFERENCES TB_OPERADORAS(REGISTRO_OPERADORA),

  COD_CONTA_CONTABIL CHAR(20) NOT NULL,
  DATA_CONTABIL DATE NOT NULL,
  DESCRICAO VARCHAR(150) NOT NULL,
  VALOR_SALDO_INICIAL DECIMAL(10) NOT NULL,
  VALOR_SALDO_FINAL DECIMAL(10) NOT NULL
);